name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code, setup Maven, cache dependencies and more...
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-distribution: 'temurin'
          java-version: '17'

      - name: Get Artifact version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Build with Maven and analyze with Sonar Cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean -Dmaven.test.skip=true -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ruizrube_iw-fullstack

      - name: Build and Deploy to GitHub Packages
        run: mvn deploy -Dmaven.test.skip=true -U -B -Pproduction
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Rename jar file
        run: mv target/*.jar target/webapp.jar
